package com.icesoft.eb;
// Generated Jun 5, 2007 2:22:49 PM by Hibernate Tools 3.2.0.b9

import static org.jboss.seam.ScopeType.SESSION;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.hibernate.validator.Pattern;

import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Scope;

/**
 * User generated by hbm2java
 */
@Entity
@Name("user")
@Scope(SESSION)
@Table(name = "Bidder")
public class User implements java.io.Serializable {

	private String username;
	private String password;
	private String name;
	private String role;   //for later use in case we expand into different roles 

        
    /** should always have an empty constructor 
     * all constructors are auto generated by icefaces-seam-gen */
    public User(){ }

	public User(String username, String password, String name) {
		this.username = username;
		this.password = password;
		this.name = name;
	}
	public User(String username, String password, String name,
			String role) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.role = role;
	}

    // added regex for validity of username similar to booking example
    @Id
	@Column(name = "username", nullable = false, length = 45)
	@NotNull
	@Length(min=5, max = 15)
    @Pattern(regex="^\\w*$", message="not a valid username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

        
    // changed the length for min of 5 to max of 15 from auto
	@Column(name = "password", nullable = false, length = 45)
	@NotNull
	@Length(min=5, max = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "role", length = 45)
	@Length(max = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}
        
    // not auto generated...we can change this to include whatever!!
    @Override
    public String toString(){
        return "User(" + username+ ")";
    }
        
}
