insert into Person (firstName,LastName,phone, email) values ('Mary','Smith', '555-2629','mary.smith@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('James','Johnson','555-3318','james.johnson@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('Patricia','Williams','555-3702','patricia.williams@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('John','Jones','555-6589','john.jones@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('Linda','Browns','555-4736','linda.brown@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('Robert','Davis','555-9732','robert.davis@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('Barbara','Miller', '555-4660','barbara.miller@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('Michael','Wilson','555-1236','michael.wilson@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('Elizabeth','Moore', '555-6653','elizabeth.moore@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('William','Taylor','555-1481','william.taylor@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('David','Garcia','555-1717','david.garcia@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('Maria','Jackson', '555-8414','maria.jackson@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('Richard','White','555-1887','richard.white@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('Susan','Harris', '555-9209','susan.harris@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('Charles','Thompson', '555-2040','charles.thompson@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('Margaret','Martinez','555-9976','margaret.martinez@icesoft.com')
insert into Person (firstName,LastName,phone, email) values ('Edward','Phillips', '555-1325','edward.phillips@icesoft.com')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Ethan','Smith','555-4562')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Jacob','Smith','555-4563')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Logan','Smith','555-4564')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Benjamin','Smith','555-4565')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Jack','Smith','555-4566')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Noah','Johnson','555-4567')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','William','Johnson','555-4568')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Andrew','Johnson','555-4569') 
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Samuel','Johnson','555-4570') 
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Joseph','Johnson','555-4571') 
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Daniel','Williams','555-4572')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Anthony','Williams','555-4573')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Angel','Williams','555-4574')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Jacob','Williams','555-4575')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','David','Williams','555-4576')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Andrew','Brown','555-4577')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Jose','Brown','555-4578')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Kitchener','Central','Joshua','Brown','555-4579')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Kitchener','Central','Christopher','Brown','555-4580')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Kitchener','Central','Matthew','Brown','555-4581')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Kitchener','Central','Ryan','Jones','555-4582')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Kitchener','Central','Jason','Jones','555-4583')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Kitchener','Central','Kevin','Jones','555-4584')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Kitchener','Central','Daniel','Jones','555-4585')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Kitchener','Centrall','Matthew','Jones','555-4586')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Kitchener','Central','Justin','Miller','555-4587')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Toronto','Central','Ethan','Miller','555-4588')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Toronto','Central','Aaron','Miller','555-4589')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Toronto','Central','Andrew','Miller','555-4590')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Toronto','Central','Vincent','Miller','555-4591')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Toronto','Central','Michael','Miller','555-4592')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Toronto','Central','Joseph','Davis','555-4593')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Toronto','Central','Daniel','Davis','555-4594')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Waterloo','Central','Matthew','Davis','555-4595')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Waterloo','Central','David','Davis','555-4596')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Waterloo','Central','Nicholas','Davis','555-4597')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Waterloo','Central','Jack','Garcia','555-4598')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Ottawa','Eastern','Alexander','Garcia','555-4590')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Ottawa','Eastern','Benjamin','Garcia','555-4591')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Ottawa','Eastern','Jacob','Garcia','555-4592')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Ottawa','Eastern','Angel','Garcia','555-4593')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Ottawa','Eastern','Christopher','Rodriguez','555-4594')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Ottawa','Eastern','Justin','Rodriguez','555-4595')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Ottawa','Eastern','Jayden','Rodriguez','555-4596')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Ottawa','Eastern','Anthony','Rodriguez','555-4597')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Halifax','Eastern','Joshua','Rodriguez','555-4598')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Halifax','Eastern','Kevin','Watson','555-4599')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Halifax','Eastern','David','Watson','555-4600')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Halifax','Eastern','Daniel','Watson','555-4601')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Halifax','Eastern','Brandon','Watson','555-4602')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('buttonsAndLinks.jspx','buttonLinks','/docs/buttonAndLinksDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('autocomplete.jspx','selectInputText','/docs/selectInputTextDoc.html','http://facestutorials.icefaces.org/tutorial/autocomplete-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-grouping.jspx','grouping','/docs/dataTableDoc.html','http://facestutorials.icefaces.org/tutorial/dataTable-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-commandSortHeader.jspx','commandSortHeader','/docs/commandSortheaderDoc.html','http://facestutorials.icefaces.org/tutorial/dataTable-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-columns.jspx','columns','/docs/columnsDoc.html','http://facestutorials.icefaces.org/tutorial/columns-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-dataScrolling.jspx','dataScrolling','/docs/dataPaginatorDoc.html','http://facestutorials.icefaces.org/tutorial/dataTable-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-expandable.jspx','expandableDataTable','/docs/expandableDoc.html','http://facestutorials.icefaces.org/tutorial/dataTable-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-resizableColumns.jspx','resizable','/docs/dataTableDoc.html','http://facestutorials.icefaces.org/tutorial/dataTable-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-rowSelection.jspx','rowSelector','/docs/tableRowSelectionDoc.html','http://facestutorials.icefaces.org/tutorial/dataTable-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('outputConnectionStatus.jspx','outputConnectionStatus','/docs/outputConnectionStatusDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('selectionTags.jspx','selection','/docs/selectionDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('textFields.jspx','textFields','/docs/textEntryDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelBorder.jspx','panelBorder','/docs/panelBorderDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelCollapsible.jspx','panelCollapsible','/docs/panelCollapsibleDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelDivider.jspx','panelDivider','/docs/panelDividerDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelPopup.jspx','panelPopup','/docs/panelPopupDoc.html','http://facestutorials.icefaces.org/tutorial/panelPopup-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelPositioned.jspx','panelPositioned','/docs/panelPositionedDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelSeries.jspx','panelSeries','/docs/panelSeriesDoc.html','http://facestutorials.icefaces.org/tutorial/seriesPanel-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('tree.jspx','tree','/docs/treeDoc.html','http://facestutorials.icefaces.org/tutorial/tree-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('selectInputDate.jspx','selectInputDate','/docs/selectInputDateDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelStack.jspx','panelStack','/docs/panelStackDoc.html','http://facestutorials.icefaces.org/tutorial/stackingPanel-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelTabSet-static.jspx','panelTabSetStatic','/docs/panelTabSetDoc.html','http://facestutorials.icefaces.org/tutorial/tabset-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelTabSet-dynamic.jspx','panelTabSetDynamic','/docs/panelTabSetDoc.html','http://facestutorials.icefaces.org/tutorial/tabset-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelTooltip.jspx','panelTooltip','/docs/panelTooltipDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('selectInputText.jspx','selectInputText','/docs/selectInputTextDoc.html','http://facestutorials.icefaces.org/tutorial/autocomplete-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('outputProgress.jspx','outputProgress','/docs/outputProgressDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('outputMedia.jspx','outputMedia','/docs/outputMediaDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('outputChart.jspx','outputChart','/docs/outputChartDoc.html','http://facestutorials.icefaces.org/tutorial/outputChart-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('menuPopup.jspx','menuPopup','/docs/menuBarDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('menuBar.jspx','menuBar','/docs/menuBarDoc.html','http://facestutorials.icefaces.org/tutorial/menuBar-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('inputRichText.jspx','inputRichText','/docs/inputRichTextDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('inputFile.jspx','inputFile','/docs/inputFileDoc.html','http://facestutorials.icefaces.org/tutorial/inputFile-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('gMap.jspx','gMap','/docs/gMapDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('effects.jspx','effects','/docs/effectsDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dragDrop.jspx','dragDrop','/docs/dragDropDoc.html','http://facestutorials.icefaces.org/tutorial/dragDrop-tutorial.html')





