insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('buttonsAndLinks.jspx','buttonLinks','/docs/buttonAndLinksDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('autocomplete.jspx','selectInputText','/docs/selectInputTextDoc.html','http://facestutorials.icefaces.org/tutorial/autocomplete-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-grouping.jspx','grouping','/docs/dataTableDoc.html','http://facestutorials.icefaces.org/tutorial/dataTable-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-commandSortHeader.jspx','commandSortHeader','/docs/commandSortheaderDoc.html','http://facestutorials.icefaces.org/tutorial/dataTable-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-columns.jspx','columns','/docs/columnsDoc.html','http://facestutorials.icefaces.org/tutorial/columns-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-dataScrolling.jspx','dataScrolling','/docs/dataPaginatorDoc.html','http://facestutorials.icefaces.org/tutorial/dataTable-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-expandable.jspx','expandableDataTable','/docs/expandableDoc.html','http://facestutorials.icefaces.org/tutorial/dataTable-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-resizableColumns.jspx','resizable','/docs/dataTableDoc.html','http://facestutorials.icefaces.org/tutorial/dataTable-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dataTable-rowSelection.jspx','rowSelector','/docs/tableRowSelectionDoc.html','http://facestutorials.icefaces.org/tutorial/dataTable-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('outputConnectionStatus.jspx','outputConnectionStatus','/docs/outputConnectionStatusDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('selectionTags.jspx','selection','/docs/selectionDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('textFields.jspx','textFields','/docs/textEntryDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelBorder.jspx','panelBorder','/docs/panelBorderDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelCollapsible.jspx','panelCollapsible','/docs/panelCollapsibleDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelDivider.jspx','panelDivider','/docs/panelDividerDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelPopup.jspx','panelPopup','/docs/panelPopupDoc.html','http://facestutorials.icefaces.org/tutorial/panelPopup-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelPositioned.jspx','panelPositioned','/docs/panelPositionedDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelSeries.jspx','panelSeries','/docs/panelSeriesDoc.html','http://facestutorials.icefaces.org/tutorial/seriesPanel-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('tree.jspx','tree','/docs/treeDoc.html','http://facestutorials.icefaces.org/tutorial/tree-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('selectInputDate.jspx','selectInputDate','/docs/selectInputDateDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelStack.jspx','panelStack','/docs/panelStackDoc.html','http://facestutorials.icefaces.org/tutorial/stackingPanel-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelTabSet-static.jspx','panelTabSetStatic','/docs/panelTabSetDoc.html','http://facestutorials.icefaces.org/tutorial/tabset-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelTabSet-dynamic.jspx','panelTabSetDynamic','/docs/panelTabSetDoc.html','http://facestutorials.icefaces.org/tutorial/tabset-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('panelTooltip.jspx','panelTooltip','/docs/panelTooltipDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('selectInputText.jspx','selectInputText','/docs/selectInputTextDoc.html','http://facestutorials.icefaces.org/tutorial/autocomplete-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('outputProgress.jspx','outputProgress','/docs/outputProgressDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('outputMedia.jspx','outputMedia','/docs/outputMediaDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('outputChart.jspx','outputChart','/docs/outputChartDoc.html','http://facestutorials.icefaces.org/tutorial/outputChart-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('menuPopup.jspx','menuPopup','/docs/menuBarDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('menuBar.jspx','menuBar','/docs/menuBarDoc.html','http://facestutorials.icefaces.org/tutorial/menuBar-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('inputRichText.jspx','inputRichText','/docs/inputRichTextDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('inputFile.jspx','inputFile','/docs/inputFileDoc.html','http://facestutorials.icefaces.org/tutorial/inputFile-tutorial.html')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('gmap.jspx','gMap','/docs/gMapDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('effects.jspx','effects','/docs/effectsDoc.html','none')
insert into MResource (pgName,lookUp,pgDoc,pgTutorial) values('dragDrop.jspx','dragDrop','/docs/dragDropDoc.html','http://facestutorials.icefaces.org/tutorial/dragDrop-tutorial.html')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Kitchener','Joshua','Brown','555-4579')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Kitchener','Christopher','Brown','555-4580')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Kitchener','Matthew','Brown','555-4581')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Kitchener','Ryan','Jones','555-4582')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Kitchener','Jason','Jones','555-4583')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Kitchener','Kevin','Jones','555-4584')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Kitchener','Daniel','Jones','555-4585')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Kitchener','Matthew','Jones','555-4586')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Kitchener','Justin','Miller','555-4587')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Toronto','Ethan','Miller','555-4588')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Toronto','Eric','Miller','555-4589')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Toronto','Andrew','Miller','555-4590')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Toronto','Vincent','Miller','555-4591')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Toronto','Michael','Miller','555-4592')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Toronto','Joseph','Davis','555-4593')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Toronto','Daniel','Davis','555-4594')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Waterloo','Matthew','Davis','555-4595')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Waterloo','David','Davis','555-4596')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Waterloo','Nicholas','Davis','555-4597')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Central','Waterloo','Jack','Garcia','555-4598')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Ottawa','Alexander','Garcia','555-4590')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Ottawa','Benjamin','Garcia','555-4591')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Ottawa','Jacob','Garcia','555-4592')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Ottawa','Angel','Garcia','555-4593')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Ottawa','Christopher','Rodriguez','555-4594')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Ottawa','Justin','Rodriguez','555-4595')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Ottawa','Jayden','Rodriguez','555-4596')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Ottawa','Anthony','Rodriguez','555-4597')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Halifax','Joshua','Rodriguez','555-4598')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Halifax','Kevin','Watson','555-4599')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Halifax','David','Watson','555-4600')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Halifax','Daniel','Watson','555-4601')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Eastern','Halifax','Brandon','Watson','555-4602')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Ethan','Smith','555-4562')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Jacob','Smith','555-4563')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Logan','Smith','555-4564')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Benjamin','Smith','555-4565')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Jack','Smith','555-4566')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Noah','Johnson','555-4567')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','William','Johnson','555-4568')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Andrew','Johnson','555-4569') 
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Calgary','Samuel','Johnson','555-4570') 
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Joseph','Johnson','555-4571') 
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Daniel','Williams','555-4572')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Anthony','Williams','555-4573')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Angel','Williams','555-4574')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Jacob','Williams','555-4575')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','David','Williams','555-4576')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Andrew','Brown','555-4577')
insert into Employee (departmentName,subdepartmentName,firstName,lastName,phone) values('Western','Victoria','Jose','Brown','555-4578')
insert into Person (firstName,LastName,phone) values ('Mary','Smith','555-2629')
insert into Person (firstName,LastName,phone) values ('James','Johnson','555-3318')
insert into Person (firstName,LastName,phone) values ('Patricia','Williams','555-3702')
insert into Person (firstName,LastName,phone) values ('John','Jones','555-6589')
insert into Person (firstName,LastName,phone) values ('Linda','Browns','555-4736')
insert into Person (firstName,LastName,phone) values ('Robert','Davis','555-9732')
insert into Person (firstName,LastName,phone) values ('Barbara','Miller', '555-4660')
insert into Person (firstName,LastName,phone) values ('Michael','Wilson','555-1236')
insert into Person (firstName,LastName,phone) values ('Elizabeth','Moore', '555-6653')
insert into Person (firstName,LastName,phone) values ('William','Taylor','555-1481')
insert into Person (firstName,LastName,phone) values ('David','Garcia','555-1717')
insert into Person (firstName,LastName,phone) values ('Maria','Jackson', '555-8414')
insert into Person (firstName,LastName,phone) values ('Richard','White','555-1887')
insert into Person (firstName,LastName,phone) values ('Susan','Harris', '555-9209')
insert into Person (firstName,LastName,phone) values ('Charles','Thompson', '555-2040')
insert into Person (firstName,LastName,phone) values ('Margaret','Martinez','555-9976')
insert into Person (firstName,LastName,phone) values ('Edward','Phillips','555-1325')