//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.19 at 02:54:15 PM MDT 
//


package com.icesoft.icefaces.resource.tutorial.component.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.icesoft.icefaces.resource.tutorial.component.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.icesoft.icefaces.resource.tutorial.component.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShipType }
     * 
     */
    public ShipType createShipType() {
        return new ShipType();
    }

    /**
     * Create an instance of {@link Fleet.Ships }
     * 
     */
    public Fleet.Ships createFleetShips() {
        return new Fleet.Ships();
    }

    /**
     * Create an instance of {@link Fleet }
     * 
     */
    public Fleet createFleet() {
        return new Fleet();
    }

}
