//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.19 at 02:54:15 PM MDT 
//


package com.icesoft.icefaces.resource.tutorial.component.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for shipFleetType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="shipFleetType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="defense"/>
 *     &lt;enumeration value="science"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "shipFleetType")
@XmlEnum
public enum ShipFleetType {

    @XmlEnumValue("defense")
    DEFENSE("defense"),
    @XmlEnumValue("science")
    SCIENCE("science");
    private final String value;

    ShipFleetType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ShipFleetType fromValue(String v) {
        for (ShipFleetType c: ShipFleetType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
