insert into Person (firstName,LastName,phoneNo, email) values ('Mary','Smith', '555-2629','mary.smith@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('James','Johnson','555-3318','james.johnson@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('Patricia','Williams','555-3702','patricia.williams@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('John','Jones','555-6589','john.jones@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('Linda','Browns','555-4736','linda.brown@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('Robert','Davis','555-9732','robert.davis@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('Barbara','Miller', '555-4660','barbara.miller@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('Michael','Wilson','555-1236','michael.wilson@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('Elizabeth','Moore', '555-6653','elizabeth.moore@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('William','Taylor','555-1481','william.taylor@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('David','Garcia','555-1717','david.garcia@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('Maria','Jackson', '555-8414','maria.jackson@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('Richard','White','555-1887','richard.white@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('Susan','Harris', '555-9209','susan.harris@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('Charles','Thompson', '555-2040','charles.thompson@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('Margaret','Martinez','555-9976','margaret.martinez@icesoft.com')
insert into Person (firstName,LastName,phoneNo, email) values ('Edward','Phillips', '555-1325','edward.phillips@icesoft.com')
insert into Employee (deptName,subDeptName,name) values('IT','Application','Martin')
insert into Employee (deptName,subDeptName,name) values('IT','Application','Robert')
insert into Employee (deptName,subDeptName,name) values('IT','Application','Xinsho')
insert into Employee (deptName,subDeptName,name) values('IT','Application','Gary')
insert into Employee (deptName,subDeptName,name) values('IT','Testing','Ryan')
insert into Employee (deptName,subDeptName,name) values('IT','Testing','Faisal')
insert into Employee (deptName,subDeptName,name) values('IT','Testing','Dan')
insert into Employee (deptName,subDeptName,name) values('IT','Development','Susan') 
insert into Employee (deptName,subDeptName,name) values('IT','Development','Allison') 
insert into Employee (deptName,subDeptName,name) values('IT','Development','Bob') 
insert into Employee (deptName,subDeptName,name) values('Marketing','Paper Media','Ali')
insert into Employee (deptName,subDeptName,name) values('Marketing','Paper Media','Damini')
insert into Employee (deptName,subDeptName,name) values('Marketing','Paper Media','John') 
insert into Employee (deptName,subDeptName,name) values('Marketing','Electronic Media','Tim')
insert into Employee (deptName,subDeptName,name) values('Sales','Internet','Ryan')
insert into Employee (deptName,subDeptName,name) values('Sales','Internet','Faisal')
insert into Employee (deptName,subDeptName,name) values('Sales','Telephonic','Dan')